### ISSUE TITLE
Nevera's Roadmap (v0)

### ISSUE THREAD

**Issue by aarvinr** [aarvinr/nevera#1]
This issue contains the roadmap and/or feature lookahead for Cron v0.

- [ ] `nevera(config)`: Initializes the router, using the given config object.
  - [ ] `style`: `"spa"` swaps page content, `"mpa"` typical browser reload.
  - [ ] `prefetch`: `"hover"` prefetches links on hover, `"auto"` prefetches all after page load, `"none"` no prefetching.
- [ ] `nevera().push(route, navigate)`: Manually pushes a new URL.
  - [ ] `route`: URL/URI to push.
  - [ ] `navigate`: `true` navigates to URL, `false` updates URL without navigating.
- [ ] `nevera().prev()`: Goes backward one page (equivalent to `history.back()`).
- [ ] `nevera().next()`: Goes forward one page (equivalent to `history.forward()`).
- [ ] `nevera().go(index)`: Goes forward/backward `index` amount of pages (equivalent to `history.go()`).
  - [ ] `index`: number representing turns (negative to go back).
